In [155]:
import pandas as pd
import numpy as np

In [156]:
df=pd.read_csv('dataset_Facebook(2).csv',sep=';')

In [157]:
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [158]:
df.shape

(500, 19)

In [159]:
df.describe()

,Page total likes,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
count,500.000000,500.000000,500.000000,500.000000,500.000000,499.000000,500.00000,5.000000e+02,500.000000,500.000000,500.000000,5.000000e+02,500.000000,500.000000,500.00000,499.000000,496.000000,500.000000
mean,123194.176000,1.880000,7.038000,4.150000,7.840000,0.278557,13903.36000,2.958595e+04,920.344000,798.772000,1415.130000,1.676638e+04,6585.488000,609.986000,7.48200,177.945892,27.266129,212.120000
std,16272.813214,0.852675,3.307936,2.030701,4.368589,0.448739,22740.78789,7.680325e+04,985.016636,882.505013,2000.594118,5.979102e+04,7682.009405,612.725618,21.18091,323.398742,42.613292,380.233118
min,81370.000000,1.000000,1.000000,1.000000,1.000000,0.000000,238.00000,5.700000e+02,9.000000,9.000000,9.000000,5.670000e+02,236.000000,9.000000,0.00000,0.000000,0.000000,0.000000
25%,112676.000000,1.000000,4.000000,2.000000,3.000000,0.000000,3315.00000,5.694750e+03,393.750000,332.500000,509.250000,3.969750e+03,2181.500000,291.000000,1.00000,56.500000,10.000000,71.000000
50%,129600.000000,2.000000,7.000000,4.000000,9.000000,0.000000,5281.00000,9.051000e+03,625.500000,551.500000,851.000000,6.255500e+03,3417.000000,412.000000,3.00000,101.000000,19.000000,123.500000
75%,136393.000000,3.000000,10.000000,6.000000,11.000000,1.000000,13168.00000,2.208550e+04,1062.000000,955.500000,1463.000000,1.486050e+04,7989.000000,656.250000,7.00000,187.500000,32.250000,228.500000
max,139441.000000,3.000000,12.000000,7.000000,23.000000,1.000000,180480.00000,1.110282e+06,11452.000000,11328.000000,19779.000000,1.107833e+06,51456.000000,4376.000000,372.00000,5172.000000,790.000000,6334.000000

In [160]:
df.isnull()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False

In [161]:
df.isnull().sum()

Page total likes                                                       0
Type                                                                   0
Category                                                               0
Post Month                                                             0
Post Weekday                                                           0
Post Hour                                                              0
Paid                                                                   1
Lifetime Post Total Reach                                              0
Lifetime Post Total Impressions                                        0
Lifetime Engaged Users                                                 0
Lifetime Post Consumers                                                0
Lifetime Post Consumptions                                             0
Lifetime Post Impressions by people who have liked your Page           0
Lifetime Post reach by people who like your Page                       0
Lifetime People who have liked your Page and engaged with your post    0
comment                                                                0
like                                                                   1
share                                                                  4
Total Interactions                                                     0
dtype: int64

In [162]:
df=df.fillna(0)

In [163]:
(df==0).sum()

Page total likes                                                         0
Type                                                                     0
Category                                                                 0
Post Month                                                               0
Post Weekday                                                             0
Post Hour                                                                0
Paid                                                                   361
Lifetime Post Total Reach                                                0
Lifetime Post Total Impressions                                          0
Lifetime Engaged Users                                                   0
Lifetime Post Consumers                                                  0
Lifetime Post Consumptions                                               0
Lifetime Post Impressions by people who have liked your Page             0
Lifetime Post reach by people who like your Page                         0
Lifetime People who have liked your Page and engaged with your post      0
comment                                                                106
like                                                                     6
share                                                                   17
Total Interactions                                                       6
dtype: int64

In [164]:
df.dtypes

Page total likes                                                         int64
Type                                                                    object
Category                                                                 int64
Post Month                                                               int64
Post Weekday                                                             int64
Post Hour                                                                int64
Paid                                                                   float64
Lifetime Post Total Reach                                                int64
Lifetime Post Total Impressions                                          int64
Lifetime Engaged Users                                                   int64
Lifetime Post Consumers                                                  int64
Lifetime Post Consumptions                                               int64
Lifetime Post Impressions by people who have liked your Page             int64
Lifetime Post reach by people who like your Page                         int64
Lifetime People who have liked your Page and engaged with your post      int64
comment                                                                  int64
like                                                                   float64
share                                                                  float64
Total Interactions                                                       int64
dtype: object

In [165]:
#SubSet Creation

In [166]:
set1=df[['Type']]
set1

       Type
0     Photo
1    Status
2     Photo
3     Photo
4     Photo
..      ...
495   Photo
496   Photo
497   Photo
498   Photo
499   Photo

[500 rows x 1 columns]

In [167]:
set2=df[['Paid']]
set2

     Paid
0     0.0
1     0.0
2     0.0
3     1.0
4     0.0
..    ...
495   0.0
496   0.0
497   0.0
498   0.0
499   0.0

[500 rows x 1 columns]

In [168]:
set3=df[['like','share']]

In [169]:
set3

       like  share
0      79.0   17.0
1     130.0   29.0
2      66.0   14.0
3    1572.0  147.0
4     325.0   49.0
..      ...    ...
495    53.0   26.0
496    53.0   22.0
497    93.0   18.0
498    91.0   38.0
499    91.0   28.0

[500 rows x 2 columns]

In [170]:
set4=df.loc[:,'Page total likes':'Lifetime Post Total Impressions']

In [171]:
set4

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions
0,139441,Photo,2,12,4,3,0.0,2752,5091
1,139441,Status,2,12,3,10,0.0,10460,19057
2,139441,Photo,3,12,3,3,0.0,2413,4373
3,139441,Photo,2,12,2,10,1.0,50128,87991
4,139441,Photo,2,12,2,3,0.0,7244,13594
...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536
496,81370,Photo,2,1,5,8,0.0,3480,6229
497,81370,Photo,1,1,5,2,0.0,3778,7216
498,81370,Photo,3,1,4,11,0.0,4156,7564
499,81370,Photo,2,1,4,4,0.0,4188,7292

In [172]:
set5=df[(df['Lifetime Post Total Reach']>1000) & (df['Lifetime Post Total Impressions']>1000)]

In [173]:
set5

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [174]:
set6=df[(df['Type']=='Photo') & (df['Lifetime Post Total Impressions']>1000)]

In [175]:
set6

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [176]:
set7=df.loc[:,'Page total likes':'Lifetime Post Impressions by people who have liked your Page']

In [177]:
set7

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534
499,81370,Photo,2,1,4,4,0.0,4188,7292,564,524,743,3861

In [178]:
small_set1=df.iloc[0:4,0:3]

In [179]:
small_set1

   Page total likes    Type  Category
0            139441   Photo         2
1            139441  Status         2
2            139441   Photo         3
3            139441   Photo         2

In [180]:
small_set2=df.iloc[0:6,0:3]

In [181]:
small_set2

   Page total likes    Type  Category
0            139441   Photo         2
1            139441  Status         2
2            139441   Photo         3
3            139441   Photo         2
4            139441   Photo         2
5            139441  Status         2

In [182]:
#Row Merge
row_m=pd.concat([small_set1,small_set2],ignore_index=True)

In [183]:
row_m

   Page total likes    Type  Category
0            139441   Photo         2
1            139441  Status         2
2            139441   Photo         3
3            139441   Photo         2
4            139441   Photo         2
5            139441  Status         2
6            139441   Photo         3
7            139441   Photo         2
8            139441   Photo         2
9            139441  Status         2

In [184]:
small_set3=df.iloc[0:4,0:3]

In [185]:
small_set4=df.iloc[0:2,1:3]

In [186]:
#Column Merge
col_m=pd.concat([small_set3, small_set4], join="inner",ignore_index=True)

In [187]:
col_m

     Type  Category
0   Photo         2
1  Status         2
2   Photo         3
3   Photo         2
4   Photo         2
5  Status         2

In [188]:
#Transpose
transposed_set=small_set1.transpose()

In [189]:
transposed_set

                       0       1       2       3
Page total likes  139441  139441  139441  139441
Type               Photo  Status   Photo   Photo
Category               2       2       3       2

In [190]:
#Reshape Of Data

In [192]:
table=pd.pivot_table(set6,values=["Page total likes","Category"],index=["Type","Paid"],aggfunc={"Page total likes":"mean","Category":"mean"})

In [193]:
table

            Category  Page total likes
Type  Paid
Photo 0.0   1.927632     122564.187500
      1.0   1.915966     122351.159664